enum DITags {
    REFRESH_TOKEN = "REFRESH_TOKEN",
    AUTH = "AUTH",
    SCHEMA = "SCHEMA",
    EMAIL = "EMAIL",
    USER = "USER",
    VERIFICATION_TOKEN = "VERIFICATION_TOKEN",
    ADMINISTRATOR = "ADMINISTRATOR",

    PAYMENT = "PAYMENT",
}
export default DITags;