enum UserEnum {
    USER = "USER",
    ADMIN = 'ADMIN',
    SUPER_ADMIN = 'SUPER_ADMIN',

    MASTER = "MASTER",
    SHOP = "SHOP",
    DESIGNER = "DESIGNER",
    MEASURER = "MEASURER",
    TEAM = "TEAM",

    EMAIL_CLIENT = "EMAIL_CLIENT",
    FACEBOOK_CLIENT = "FACEBOOK_CLIENT",
    LINKEDIN_CLIENT = "LINKEDIN_CLIENT",
    VK_CLIENT = "VK_CLIENT",
    TIKTOK_CLIENT = "TIKTOK_CLIENT"
}

export default UserEnum;